version: '3'

services:
  mysqldbservice:
    container_name: mysqldb
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    restart: unless-stopped
    volumes:
      - mysqldb:/var/lib/mysql
  app:
    container_name: userandtransaction
    depends_on:
      - mysqldbservice
    image: userandtransaction
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://$CONTAINER:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=$MYSQLDB_USER
      - SPRING_DATASOURCE_PASSWORD=$MYSQLDB_ROOT_PASSWORD
    restart: on-failure
    volumes:
      - .m2:/root/.m2

volumes:
  mysqldb:

